version: '3'
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: mystry007
      WORDPRESS_DB_NAME: wordpressDB
  
  db:     
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bond007
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: mystry007
      MYSQL_DATABASE: wordpressDB
      expose:
        - "3306"
      volumes:
        - /home/saurabh/msqlData:/var/lib/mysql
